#############################################################

[globals]
  # How many times to collect usage statistics
  statsiterations=5
  
  # How long to wait in seconds between collecting statistics
  statsinterval=2

  # Output file name
  outputfile="output.csv"

# Host Needs only 1 member of the cluster will autodiscover the rest
[nodes]
  [nodes.host1]
    host="localhost:30001"
  [nodes.host2]
    host="localhost:30001"