#############################################################

[globals]
  # How many times to collect usage statistics
  statsiterations=360
  
  # How long to wait in seconds between collecting statistics
  statsinterval=10

  # Output file name
  outputfile="output.csv"

# Host Needs only 1 member of the cluster will autodiscover the rest
[clusters]
  [clusters.staging]
    host="localhost:30001"
    #password="mypassword"
    #ssl=true

#############################################################
# Example Mulitple clusters
#
#[globals]
#  # How many times to collect usage statistics
#  statsiterations=360
#  
#  # How long to wait in seconds between collecting statistics
#  statsinterval=10
#
#  # Output file name
#  outputfile="output.csv"
#
## Host Needs only 1 member of the cluster will autodiscover the rest
#[clusters]
#  [clusters.staging]
#    host="stage-host:30001"
#    ssl=false
#    password="1234"
#  [clusters.production]
#    host="prod-host:30001"
#    password="s00perSecr3t"
#    ssl=true
